on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build nntask1 executable
        run: pushd nntask1 && cargo build --release && popd
      - name: Build nntask2 executable
        run: pushd nntask2 && cargo build --release && popd
      - name: Build nntask3 executable
        run: pushd nntask3 && cargo build --release && popd
      - name: Build nntask4 executable
        run: pushd nntask4 && cargo build --release && popd
      - name: Copy artifacts
        run: |
          cp nntask1/target/release/nntask1.exe .
          cp nntask2/target/release/nntask2.exe .
          cp nntask3/target/release/nntask3.exe .
          cp nntask4/target/release/nntask4.exe .
          cp report/report.pdf .
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-neural
          path: |
            tests
            tester.bat
            nntask1.exe
            nntask2.exe
            nntask3.exe
            nntask4.exe
            report.pdf
